import "styles/globals.css";
import type { Metadata } from "next";
import Provider from "@/components/Provider";

export const metadata: Metadata = {
  title: "NFC Scanner",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={"relative bg-gray-400"}>
        <Provider>
          <main className="app">{children}</main>
        </Provider>
      </body>
    </html>
  );
}
